#!/bin/bash

OLDSYS=korean-v10t
NEWSYS=ca-donut

function do_stuff() {
installold etc 
installold usr
installold 3rd_party 
installold bin 
installold busybox 
installold fonts 
installold lib 
installold media
installold sounds 
installold xbin 


#-- Install framework
mkdir framework
#Copy from ca-donut
install framework/am.jar #same as on korean-v10t
install framework/svc.jar #same as on korean-v10t
install framework/android.test.runner.jar #very minor changes, what does that do anyway?
install framework/bmgr.jar #same as
install framework/ext.jar #very minor differences
install framework/framework-tests.jar #same as
install framework/ime.jar #same as
install framework/input.jar #same as
install framework/pm.jar #same as korean-v10t
install framework/monkey.jar #this is for automated application testing. lg added switch '--hprof-all', we ignore this for now
install framework/android.policy.jar #This makes the keyguard unreadably
install framework/core.jar #dropped LG's changes. They were something regarding PBEParametersGenerator replaced by PKCS12ParametersGenerator and more
install framework/framework-res.apk #files added by lg: res/drawable/stat_sys_gps_acquiring_1.png res/layout/lge_time_picker.xml res/layout/lge_time_picker_dialog.xml res/layout/search_dropdown_item_2line.xml   
resign framework/framework-res.apk

#Compile files from deodex/korean-v10t/framework/...
#deodex framework/android.policy #what is changed in here?
#deodex framework/core #there are just 10 files or so changed, so someone should look into that
deodex framework/com.google.android.gtalkservice #this is proprietary
deodex framework/com.google.android.maps #this is proprietary
deodex framework/framework
deodex framework/services
deodex framework/qcnvitems #this is proprietary
deodex framework/qcrilhook #this is proprietary

#Copy directly from korean-v10t
#installold framework/framework-res.apk
#resign framework/framework-res.apk
installold framework/lge-res.apk #proprietary
resign framework/lge-res.apk #propriertary


#-- Install app
mkdir app
#-Changed by LG:
#deodex app/SoundRecorder
#deodex app/CalendarProvider
#deodex app/AlarmClock
#deodex app/GoogleSubscribedFeedsProvider
#deodex app/Browser
#deodex app/Calendar
#deodex app/DownloadProvider
#deodex app/Music
#deodex app/Launcher
#deodex app/Contacts
#deodex app/GoogleContactsProvider
#deodex app/Phone
#deodex app/MediaProvider
#deodex app/TelephonyProvider
#deodex app/Camera

#-Added by LG:
#deodex app/Homeselector #Select which homescreen you want
#deodex app/Homecube #LG's homescreen
deodex app/Memo #?
deodex app/ChargingTest #?
deodex app/DrmDataMngr #?
deodex app/DrmService #?
deodex app/FavoriteContacts #Favourite Contacts app
deodex app/HiddenMenu #The famous HiddenMenu
deodex app/ELTTest #?
deodex app/Linkbook #SNS application
deodex app/LGSetupWizard #?
deodex app/LgeFmRadio #FM Radio
deodex app/LGSystemProvider #?
deodex app/OTA #What does this do? over-the-air updates?
deodex app/orangephorowidget #what does this do?
deodex app/PowerOff #The dialog that appears when pressing the power off button
deodex app/RingsExtended #?
deodex app/SimChecker #?
deodex app/Stk #Sim toolkit

#Copy from (patched) ca-donut
install app/Settings.apk
install app/SettingsProvider.apk
install app/Mms.apk
install app/GoogleSearch.apk #Differences have been patched into source, just minor remaining
install app/Launcher.apk

#Copy unchanged apps
install app/Browser.apk #A lot of changes. Test for regressions
install app/Phone.apk #There are a lot, a lot, a lot changes. Test regressions!  (bluetooth etc)
install app/AlarmClock.apk #some changes, test for regressions
install app/GoogleSubscribedFeedsProvider.apk #I dont even know what this does
install app/CalendarProvider.apk #Some changes, test for regressions!
install app/Calendar.apk #Some changes, test for regressions!
install app/Camera.apk #dropped. There are a lot of changes so test for regressions!
install app/TelephonyProvider.apk #dropped. changes were: some additional field in sms/mms storage, and something about APN settings
install app/Music.apk #dropping lg's changes
install app/DownloadProvider.apk #dropping lg's changes (DRM)
install app/MediaProvider.apk #dropping lg's changes (DRM)
install app/Launcher.apk #dropping lg's changes (minor)
install app/Contacts.apk #dropping lg's changes
install app/GoogleContactsProvider.apk #dropping lg's changes
install app/SoundRecorder.apk
install app/GlobalSearch.apk #has only very minor differences
install app/PackageInstaller.apk #not changed
install app/HTMLViewer.apk #not changed
install app/ApplicationsProvider.apk #not changed
install app/DrmProvider.apk #not changed in korean-v10t
install app/VpnServices.apk #not changed
install app/TtsService.apk #not changed
install app/UserDictionaryProvider.apk #not changed
install app/PicoTts.apk #not changed
install app/Calculator.apk #very minor changes

#Copy apps that are only in ca-donut
install app/SpareParts.apk #Some nice utilities

#those are not in odex form
#installold app/toleSetup.apk
installold app/WeatherApp.apk
#installold app/cz.romario.opensudoku.apk
installold app/EnhancedGoogleSearchProvider.apk #this needs to be resigned for shared uid
#installold app/com.stain46.taghome16.apk
#installold app/com.betterandroid.betterkeyboard.apk
installold app/NetworkLocation.apk
installold app/XIM.apk
installold app/lgecamera.apk #in uid.media
installold app/DivxRegistration.apk #in uid.media
installold app/ArcMediaGallery.apk #in uid.media
installold app/ArcMMP.apk #in uid.media
#installold app/com.mathpad.mobile.android.wt.unit.apk
#installold app/com.motalen.batterytimelite.apk
#installold app/com.twidroid.apk
#installold app/com.farproc.wifi.analyzer.apk
#installold app/com.androidapps.widget.weather2.apk
#installold app/com.pocketools.currency.apk
#installold app/com.jiuzhangtech.rushhour.apk
#installold app/kr.mobilesoft.yxflash.apk
installold app/WifiService.apk
installold app/GoogleCheckin.apk #in uid.system
installold app/ArcWorkshop.apk #in uid.media
installold app/ArcVideoEditor.apk #in uid.media
#installold app/org.adw.launcher_donut.apk
#installold app/Maps.apk #is in market
#installold app/aDosBox.apk
#installold app/com.google.zxing.client.android.apk
#installold app/alterforce.jewellust_lite.apk

echo Resigning all under app/
for i in `find app -name '*.apk'`
do
  resign $i
done


#The apps in here are exactly those who have been signed by Google
GAPPS="app/Vending.apk app/Gmail.apk app/GmailProvider.apk app/GoogleApps.apk app/GooglePartnerSetup.apk app/GoogleSettingsProvider.apk app/gtalkservice.apk app/ImProvider.apk app/MarketUpdater.apk app/MediaUploader.apk app/SetupWizard.apk app/Street.apk app/Talk.apk app/YouTube.apk app/Maps.apk"

#Gapps must not be resigned!
#or you will get com.google.android.googlelogin.GoogleLoginServiceNotFoundException: The Google login service cannot be verified
echo Copying Google apps
for i in $GAPPS
do
  if [[ -e ../$OLDSYS/app/$(basename $i .apk).odex ]]; then
    echo "Error GoogleApp is only available in odex!"
    exit 1
  fi
  installold $i
done


echo Copying additional apps
#those are not in odex form
installold app/com.android.stopwatch.apk
#installold app/toleSetup.apk
#installold app/WeatherApp.apk
installold app/bz.ktk.bubble.apk
installold app/com.speedsoftware.rootexplorer.apk
installold app/com.appdroid.anycut.apk
#installold app/cz.romario.opensudoku.apk
installold app/Quickoffice.apk
#installold app/EnhancedGoogleSearchProvider.apk
installold app/koushikdutta.superuser.apk
#installold app/com.stain46.taghome16.apk
#installold app/com.betterandroid.betterkeyboard.apk
#installold app/com.mathpad.mobile.android.wt.unit.apk
#installold app/com.motalen.batterytimelite.apk
#installold app/com.twidroid.apk
#installold app/com.farproc.wifi.analyzer.apk
installold app/com.arron.taskManagerFree.apk
installold app/com.eclipsim.gpsstatus2.apk
#installold app/com.androidapps.widget.weather2.apk
#installold app/com.pocketools.currency.apk
installold app/whiteCompass.apk
#installold app/com.jiuzhangtech.rushhour.apk
#installold app/kr.mobilesoft.yxflash.apk
#installold app/org.adw.launcher_donut.apk
#installold app/Maps.apk #is in market
installold app/My_e-mail_Android.apk
#installold app/aDosBox.apk
#installold app/com.google.zxing.client.android.apk
installcustom app/com.keramidas.TitaniumBackup.apk

install etc/security/cacerts.bks 
install etc/security/otacerts.zip

#Copy standard su
install xbin/su
mv xbin/su xbin/su2
chmod 4555 xbin/su2

#Copy SuperUser whitelist's su
cp bin/su xbin/su
chmod 4555 bin/su
chmod 4555 xbin/su

cp ../../my-boot/my-kernel/drivers/net/wireless/bcm4325/wireless.ko lib/modules/

cp usr/keylayout/eve_qwerty.kl usr/keylayout/eve_qwerty.kl-english
installcustom usr/keylayout/eve_qwerty.kl-german

installcustom build.prop
}


