#!/bin/bash

OLDSYS=korean-v10t
NEWSYS=ca-donut

function do_stuff() {
installold etc 
installold usr
installold 3rd_party 
installold bin 
installold busybox 
installold fonts 
installold lib 
installold media
installold sounds 
installold xbin 
installold build.prop


#-- Install framework
mkdir framework
#Copy from ca-donut
install framework/am.jar #same as on korean-v10t
install framework/svc.jar #same as on korean-v10t
install framework/android.test.runner.jar #very minor changes, what does that do anyway?
install framework/bmgr.jar #same as
install framework/ext.jar #very minor differences
install framework/framework-tests.jar #same as
install framework/ime.jar #same as
install framework/input.jar #same as
install framework/pm.jar #same as korean-v10t

#Compile files from deodex/korean-v10t/framework/...
deodex framework/android.policy #what is changed in here?
deodex framework/core #there are just 10 files or so changed, so someone should look into that
deodex framework/com.google.android.gtalkservice #this is proprietary
deodex framework/com.google.android.maps #this is proprietary
deodex framework/framework
deodex framework/monkey #what is this for?
deodex framework/services
deodex framework/qcnvitems
deodex framework/qcrilhook

#Copy directly from korean-v10t
installold framework/framework-res.apk
resign framework/framework-res.apk
installold framework/lge-res.apk
resign framework/lge-res.apk


#-- Install app
mkdir app
#for i in `find ../$OLDSYS/app -name '*.odex'`
#do
#  I=$(basename $i .odex)
#  echo deodex app/$I
#  deodex app/$I
#done
deodex app/SoundRecorder
deodex app/PowerOff
deodex app/GlobalSearch
deodex app/Homecube
deodex app/ELTTest
deodex app/CalendarProvider
deodex app/ApplicationsProvider
deodex app/LGSetupWizard
deodex app/HiddenMenu
deodex app/Linkbook
deodex app/AlarmClock
deodex app/ChargingTest
deodex app/DrmDataMngr
deodex app/GoogleSubscribedFeedsProvider
deodex app/Browser
deodex app/Calendar
deodex app/LgeFmRadio
deodex app/DownloadProvider
deodex app/Music
deodex app/LGSystemProvider
deodex app/Launcher
deodex app/RingsExtended
deodex app/GoogleSearch
deodex app/Memo
deodex app/Contacts
deodex app/DrmService
deodex app/SimChecker
deodex app/FavoriteContacts
deodex app/Stk
deodex app/GoogleContactsProvider
deodex app/orangephorowidget
deodex app/HTMLViewer
deodex app/Phone
deodex app/MediaProvider
deodex app/PackageInstaller
deodex app/TelephonyProvider
deodex app/UserDictionaryProvider
deodex app/OTA
deodex app/Camera
deodex app/PicoTts
deodex app/Homeselector
deodex app/Calculator

#Copy from ca-donut
install app/Settings.apk
install app/SettingsProvider.apk
install app/Mms.apk
install app/DrmProvider.apk #not changed in korean-v10t
install app/VpnServices.apk #not changed
install app/TtsService.apk #not changed

#those are not in odex form
#installold app/toleSetup.apk
installold app/WeatherApp.apk
#installold app/cz.romario.opensudoku.apk
installold app/EnhancedGoogleSearchProvider.apk #this needs to be resigned for shared uid
#installold app/com.stain46.taghome16.apk
#installold app/com.betterandroid.betterkeyboard.apk
installold app/NetworkLocation.apk
installold app/XIM.apk
installold app/lgecamera.apk #in uid.media
installold app/DivxRegistration.apk #in uid.media
installold app/ArcMediaGallery.apk #in uid.media
installold app/ArcMMP.apk #in uid.media
#installold app/com.mathpad.mobile.android.wt.unit.apk
#installold app/com.motalen.batterytimelite.apk
#installold app/com.twidroid.apk
#installold app/com.farproc.wifi.analyzer.apk
#installold app/com.androidapps.widget.weather2.apk
#installold app/com.pocketools.currency.apk
#installold app/com.jiuzhangtech.rushhour.apk
#installold app/kr.mobilesoft.yxflash.apk
installold app/WifiService.apk
installold app/GoogleCheckin.apk #in uid.system
installold app/ArcWorkshop.apk #in uid.media
installold app/ArcVideoEditor.apk #in uid.media
#installold app/org.adw.launcher_donut.apk
#installold app/Maps.apk #is in market
#installold app/aDosBox.apk
#installold app/com.google.zxing.client.android.apk
#installold app/alterforce.jewellust_lite.apk

echo Resigning all under app/
for i in `find app -name '*.apk'`
do
  resign $i
done


#The apps in here are exactly those who have been signed by Google
GAPPS="app/Vending.apk app/Gmail.apk app/GmailProvider.apk app/GoogleApps.apk app/GooglePartnerSetup.apk app/GoogleSettingsProvider.apk app/gtalkservice.apk app/ImProvider.apk app/MarketUpdater.apk app/MediaUploader.apk app/SetupWizard.apk app/Street.apk app/Talk.apk app/YouTube.apk app/Maps.apk"

#Gapps must not be resigned!
#or you will get com.google.android.googlelogin.GoogleLoginServiceNotFoundException: The Google login service cannot be verified
echo Copying Google apps
for i in $GAPPS
do
  if [[ -e ../$OLDSYS/app/$(basename $i .apk).odex ]]; then
    echo "Error GoogleApp is only available in odex!"
    exit 1
  fi
  installold $i
done


echo Copying additional apps
#those are not in odex form
installold app/com.android.stopwatch.apk
#installold app/toleSetup.apk
#installold app/WeatherApp.apk
installold app/bz.ktk.bubble.apk
installold app/com.speedsoftware.rootexplorer.apk
installold app/com.appdroid.anycut.apk
#installold app/cz.romario.opensudoku.apk
installold app/Quickoffice.apk
#installold app/EnhancedGoogleSearchProvider.apk
installold app/koushikdutta.superuser.apk
#installold app/com.stain46.taghome16.apk
#installold app/com.betterandroid.betterkeyboard.apk
#installold app/com.mathpad.mobile.android.wt.unit.apk
#installold app/com.motalen.batterytimelite.apk
#installold app/com.twidroid.apk
#installold app/com.farproc.wifi.analyzer.apk
installold app/com.arron.taskManagerFree.apk
installold app/com.eclipsim.gpsstatus2.apk
#installold app/com.androidapps.widget.weather2.apk
#installold app/com.pocketools.currency.apk
installold app/whiteCompass.apk
#installold app/com.jiuzhangtech.rushhour.apk
#installold app/kr.mobilesoft.yxflash.apk
#installold app/org.adw.launcher_donut.apk
#installold app/Maps.apk #is in market
installold app/My_e-mail_Android.apk
#installold app/aDosBox.apk
#installold app/com.google.zxing.client.android.apk
installcustom app/com.keramidas.TitaniumBackup.apk

install etc/security/cacerts.bks 
install etc/security/otacerts.zip

#Copy standard su
install xbin/su
mv xbin/su xbin/su2
chmod 4555 xbin/su2

#Copy SuperUser whitelist's su
cp bin/su xbin/su
chmod 4555 bin/su
chmod 4555 xbin/su

cp ../../my-boot/my-kernel/drivers/net/wireless/bcm4325/wireless.ko lib/modules/

cp usr/keylayout/eve_qwerty.kl usr/keylayout/eve_qwerty.kl-english
installcustom usr/keylayout/eve_qwerty.kl-german
}


