#!/bin/bash

set -e #exit on error
set -u #error on unset variable

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 cmdfile"
    exit 1
fi

source $1

echo "Building from $NEWSYS..."

OUTIMG=system.img
SMALI=../smali-1.2.3.jar
BAKSMALI=../baksmali-1.2.3.jar
MKYAFFS2IMAGE=../$NEWSYS/out/host/linux-x86/bin/mkyaffs2image
SIGNAPK=../$NEWSYS/out/host/linux-x86/framework/signapk.jar
ZIPALIGN=../$NEWSYS/out/host/linux-x86/bin/zipalign
KEYDIR=../$NEWSYS/build/target/product/security

function resign() {
  #To fix E/PackageManager(  681): Package foobar has no signatures that match those in shared user android.uid.system; ignoring!
  java -jar ../$SIGNAPK ../$KEYDIR/platform.x509.pem ../$KEYDIR/platform.pk8 $1 $1-signed
  rm "$1"
  ../$ZIPALIGN 4 $1-signed $1
  rm "$1-signed"
}
 

function install() {
  if [[ -d ../$NEWSYS/$1 && -d $1 ]];then
    cp -af ../$NEWSYS/$1/* $1/
  else
    cp -af ../$NEWSYS/$1 $1
  fi
}

function installold() {
  NEWSYS="$OLDSYS" install $1
}

function installcustom() {
  if [[ $# -eq 1 ]];then
    cp -fa ../custom/$1 $1
  else
    cp -fa ../custom/$1 $2
  fi
}

function deodex() {

  if [[ ! -d ../deodex/$OLDSYS/$1 ]]; then
    echo "Deodexing $1"
    mkdir -p ../deodex/$OLDSYS/$1
    java -jar ../$BAKSMALI -d ../$OLDSYS/framework -x ../$OLDSYS/$1.odex -o ../deodex/$OLDSYS/$1/
  fi

  if [[ ! -f ../deodex/$OLDSYS/$1/classes.dex ]]; then
    echo "Compiling $1"
    rm -Rf ../temp
    mkdir ../temp
    java -Xmx512M -jar ../$SMALI ../deodex/$OLDSYS/$1 -o ../deodex/$OLDSYS/$1/classes.dex
  fi

  if [[ -f ../$OLDSYS/$1.jar ]]; then
    ARCHIVE="$1.jar"
  elif [[ -f ../$OLDSYS/$1.apk ]]; then
    ARCHIVE="$1.apk"
  else
    echo "ERROR: no archive apk/jar for $1 found!"
    exit 1
  fi

  if [[ ! -f ../deodex/$OLDSYS/$ARCHIVE ]];then
    echo "Packing $1 into $ARCHIVE"
    cp -fa ../$OLDSYS/$ARCHIVE ../deodex/$OLDSYS/$ARCHIVE
    #zip --junk-paths -u $ARCHIVE ../deodex/$OLDSYS/$1/classes.dex
    7z a -tzip ../deodex/$OLDSYS/$ARCHIVE ../deodex/$OLDSYS/$1/classes.dex -mx5 > /dev/null
  fi
  cp ../deodex/$OLDSYS/$ARCHIVE $ARCHIVE
}

if [[ ! -d $OLDSYS ]]; then
  echo "ERROR: directory $OLDSYS does not exist!"
  echo "Extract korean-v10t system.img to that directory or run"
  echo "adb pull /system $OLDSYS with korean-v10t (by zacpod) installed"
  exit 1
fi

if [[ ! -d $NEWSYS ]]; then
  echo "Directory $NEWSYS does not exist"
  echo "This should be a link to ../$NEWSYS/out/target/product/openetna/system"
  echo "Execute: ln -s ../$NEWSYS/out/target/product/openetna/system $NEWSYS"
  exit 1
fi

rm -fR temp && mkdir temp

rm -fR system && \
mkdir system && \
cd system

do_stuff

cd .. 
$MKYAFFS2IMAGE -f ./system $OUTIMG
7z a -tzip system.zip system.img
rm -Rf temp
