#!/bin/bash
#Call with argument -c to copy different files to phone

adb shell 'busybox find system -type f | busybox xargs busybox md5sum' | dos2unix | sort > /tmp/android-phone 
find system -type f | xargs md5sum | sort > /tmp/android-here


comm -1  -3 /tmp/android-phone /tmp/android-here | cut -d' ' -f3 | sort > /tmp/android-only-here
comm -2  -3 /tmp/android-phone /tmp/android-here | cut -d' ' -f3 | sort > /tmp/android-only-phone
comm -1 -2 /tmp/android-only-here /tmp/android-only-phone > /tmp/android-modified

#adb shell busybox md5sum 'system' | dos2unix | md5sum -c --quiet  - | tee /tmp/android-diff-framework
#echo Checking /system/app
#adb shell busybox md5sum 'system/app/*' | dos2unix | md5sum -c --quiet - | tee /tmp/android-diff-app

echo "To delete:"
cat /tmp/android-only-phone
echo "To upload:"
cat /tmp/android-only-here


if [[ -f system/useEmulator ]]; then
  echo "system/useEmulator exists, so I won't let you upload the different files"
  exit 
fi

echo "If you do not want to sync, press Ctrl-C now"
if read; then
  echo "Deleting"
  cat /tmp/android-only-phone | xargs -n1 adb shell busybox rm
  cat /tmp/android-only-here | while read FILE
  do
    echo "$FILE -> $FILE"
    adb push $FILE $FILE
  done
fi

echo "If you do not want to 'adb shell reboot', press Ctrl-C now"
if read; then
  adb shell reboot
fi
