#!/bin/bash
if [[ $# -le 1 ]]; then
  echo "Call $0 SystemVersionNumber [BootVersionNumber]"
  exit 1
fi
if [[ ! -f system.img || ! -d system ]]; then
  echo "ERROR: system.img or system/ does not exist!"
  exit 1
fi

if [[ -f system/do_no_release ]]; then
  echo "ERROR: system/do_no_release exists!"
  exit 1
fi

mkdir -p Images

echo "Packing system"
cp -a system.img Images/systemV$1.img
rm -Rf Images/systemV$1
cp -a system Images/systemV$1
rm -f Images/systemV$1.7z
7z a -t7z -mx9 Images/systemV$1.7z Images/systemV$1.img

if [[ $# -eq 2 ]]; then
  echo "Packing boot"
  cp ../android-2.1/out/target/product/openetna/boot.img Images/bootV$2.img
fi
