#!/bin/bash
set -e #exit on error
set -u #error on unset variable

#get md5sums of files on the phone
#remove lines starting with '*' to remove the adb messages
#"* daemon not running. starting it now *"
#and "* daemon started successfully *"

adb shell 'busybox find system -type f | busybox xargs busybox md5sum' | dos2unix | sed '/^\*/d' | sort > /tmp/android-phone 
find system -type f | xargs md5sum | sort > /tmp/android-here


comm -1  -3 /tmp/android-phone /tmp/android-here | cut -d' ' -f3 | sort > /tmp/android-only-here
comm -2  -3 /tmp/android-phone /tmp/android-here | cut -d' ' -f3 | sed '/system\/bin\/busybox/d' |sort > /tmp/android-only-phone
comm -2 -3 /tmp/android-only-phone /tmp/android-only-here > /tmp/android-to-delete


#adb shell busybox md5sum 'system' | dos2unix | md5sum -c --quiet  - | tee /tmp/android-diff-framework
#echo Checking /system/app
#adb shell busybox md5sum 'system/app/*' | dos2unix | md5sum -c --quiet - | tee /tmp/android-diff-app

echo "To delete:"
cat /tmp/android-to-delete
echo "To upload:"
cat /tmp/android-only-here


if [[ -f system/useEmulator ]]; then
  echo "system/useEmulator exists, so I won't let you upload the different files"
  exit 
fi

echo "If you do not want to sync, press Ctrl-C now, else enter to continue"
if read; then
  echo "Deleting"
  cat /tmp/android-to-delete | xargs --no-run-if-empty -n1 adb shell busybox rm
  cat /tmp/android-only-here | while read FILE
  do
    echo "$FILE -> $FILE"
    adb push $FILE $FILE
  done
fi

echo "If you do not want to 'adb reboot', press Ctrl-C now, else enter to continue"
if read; then
  adb reboot
fi
