#!/bin/bash
( cd my-root/ && find . | cpio -o -H newc | gzip > ../debug-ramdisk.cpio.gz )

#RAMDISK=zacpod-v10t-ramdisk.gz
RAMDISK=debug-ramdisk.cpio.gz

../android-2.1/out/host/linux-x86/bin/mkbootimg --cmdline 'root=/dev/mtdblock1 rootfstype=yaffs2 lpj=1912832 console=/dev/null' --kernel ../android-2.1/out/target/product/openetna/kernel --ramdisk $RAMDISK -o boot.img
echo "Don't forget to update the drivers on the phone under /system/lib/modules, if there were changes"
